# Generated by Django 5.1.5 on 2025-02-14 11:46

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_premises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('lk', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Type_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_lightbulb.room_type_category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lk', models.IntegerField()),
                ('ra', models.IntegerField()),
                ('k', models.IntegerField(blank=True, null=True, verbose_name='Pulsatsiya')),
                ('table_height', models.FloatField(blank=True, default=0.8, null=True, verbose_name='Ish stoli balandligi')),
                ('color_tem', models.CharField(blank=True, max_length=200, null=True)),
                ('light_type', models.CharField(max_length=200)),
                ('recommended_lamps', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_lightbulb.room_type_category')),
            ],
        ),
    ]
