# Generated by Django 5.1.5 on 2025-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lightbulb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_of_premises',
            name='lk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
