# Generated by Django 5.1.5 on 2025-02-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lightbulb', '0002_room_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_type',
            name='name',
        ),
    ]
