# Generated by Django 5.1.5 on 2025-02-14 10:29

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lightbulb', '0002_alter_type_of_premises_lk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Type_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_lightbulb.room_type_category')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('lk', models.IntegerField()),
                ('ra', models.IntegerField()),
                ('k', models.IntegerField(blank=True, null=True, verbose_name='Pulsatsiya')),
                ('table_height', models.FloatField(blank=True, default=0.8, null=True, verbose_name='Ish stoli balandligi')),
                ('color_tem', models.CharField(blank=True, max_length=200, null=True)),
                ('light_type', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_lightbulb.room_type_category')),
            ],
        ),
    ]
