# Generated by Django 5.1.5 on 2025-02-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lightbulb', '0003_room_type_category_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='recommended_lamps',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
