# Generated by Django 5.1.5 on 2025-03-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lightbulb', '0004_room_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_type',
            old_name='color_tem',
            new_name='razreyd',
        ),
        migrations.RenameField(
            model_name='room_type',
            old_name='light_type',
            new_name='ugr',
        ),
    ]
