# Generated by Django 5.1.5 on 2025-02-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lightbulb', '0005_room_type_category_level_room_type_category_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_type',
            name='name',
        ),
        migrations.AlterField(
            model_name='room_type_category',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
